/*
Copyright The Helm Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package provenance

import (
	"crypto"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	pgperrors "github.com/ProtonMail/go-crypto/openpgp/errors"
	"github.com/ProtonMail/go-crypto/openpgp/packet"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"sigs.k8s.io/yaml"

	"helm.sh/helm/v4/pkg/chart/v2/loader"
)

const (
	// testKeyFile is the secret key.
	// Generating keys should be done with `gpg --gen-key`. The current key
	// was generated to match Go's defaults (RSA/RSA 2048). It has no pass
	// phrase. Use `gpg --export-secret-keys helm-test` to export the secret.
	testKeyfile = "testdata/helm-test-key.secret"

	// testPasswordKeyfile is a keyfile with a password.
	testPasswordKeyfile = "testdata/helm-password-key.secret"

	// testPubfile is the public key file.
	// Use `gpg --export helm-test` to export the public key.
	testPubfile = "testdata/helm-test-key.pub"

	// Generated name for the PGP key in testKeyFile.
	testKeyName = `Helm Testing (This key should only be used for testing. DO NOT TRUST.) <helm-testing@helm.sh>`

	testPasswordKeyName = `password key (fake) <fake@helm.sh>`

	testChartfile = "testdata/hashtest-1.2.3.tgz"

	// testSigBlock points to a signature generated by an external tool.
	// This file was generated with GnuPG:
	// gpg --clearsign -u helm-test --openpgp testdata/msgblock.yaml
	testSigBlock = "testdata/msgblock.yaml.asc"

	// testTamperedSigBlock is a tampered copy of msgblock.yaml.asc
	testTamperedSigBlock = "testdata/msgblock.yaml.tampered"

	// testMixedKeyring points to a keyring containing RSA and ed25519 keys.
	testMixedKeyring = "testdata/helm-mixed-keyring.pub"

	// testSumfile points to a SHA256 sum generated by an external tool.
	// We always want to validate against an external tool's representation to
	// verify that we haven't done something stupid. This file was generated
	// with shasum.
	// shasum -a 256 hashtest-1.2.3.tgz > testdata/hashtest.sha256
	testSumfile = "testdata/hashtest.sha256"
)

// testMessageBlock represents the expected message block for the testdata/hashtest chart.
const testMessageBlock = `apiVersion: v1
description: Test chart versioning
name: hashtest
version: 1.2.3

...
files:
  hashtest-1.2.3.tgz: sha256:c6841b3a895f1444a6738b5d04564a57e860ce42f8519c3be807fb6d9bee7888
`

// loadChartMetadataForSigning is a test helper that loads chart metadata and marshals it to YAML bytes
func loadChartMetadataForSigning(t *testing.T, chartPath string) []byte {
	t.Helper()

	chart, err := loader.LoadFile(chartPath)
	require.NoError(t, err)

	metadataBytes, err := yaml.Marshal(chart.Metadata)
	require.NoError(t, err)

	return metadataBytes
}

func TestMessageBlock(t *testing.T) {
	metadataBytes := loadChartMetadataForSigning(t, testChartfile)

	// Read the chart file data
	archiveData, err := os.ReadFile(testChartfile)
	require.NoError(t, err)

	out, err := messageBlock(archiveData, filepath.Base(testChartfile), metadataBytes)
	require.NoError(t, err)
	got := out.String()

	if got != testMessageBlock {
		assert.Equal(t, testMessageBlock, got)
	}
}

func TestParseMessageBlock(t *testing.T) {
	sc, err := parseMessageBlock([]byte(testMessageBlock))
	require.NoError(t, err)

	// parseMessageBlock only returns checksums, not metadata (like upstream)

	if lsc := len(sc.Files); lsc != 1 {
		assert.Equal(t, 1, lsc)
	}

	if hash, ok := sc.Files["hashtest-1.2.3.tgz"]; !ok {
		assert.Fail(t, "hashtest file not found in Files")
	} else if hash != "sha256:c6841b3a895f1444a6738b5d04564a57e860ce42f8519c3be807fb6d9bee7888" {
		assert.Equal(t, "hashtest", hash)
	}
}

func TestLoadKey(t *testing.T) {
	k, err := loadKey(testKeyfile)
	require.NoError(t, err)

	if _, ok := k.Identities[testKeyName]; !ok {
		assert.NotNil(t, k, "Expected to load a key for user %q", testKeyName)
	}
}

func TestLoadKeyRing(t *testing.T) {
	k, err := loadKeyRing(testPubfile)
	require.NoError(t, err)

	if len(k) > 1 {
		assert.Len(t, k, 1)
	}

	for _, e := range k {
		if ii, ok := e.Identities[testKeyName]; !ok {
			assert.Contains(t, ii.Name, testKeyName)
		}
	}
}

func TestDigest(t *testing.T) {
	f, err := os.Open(testChartfile)
	require.NoError(t, err)
	defer f.Close()

	hash, err := Digest(f)
	require.NoError(t, err)

	sig, err := readSumFile(testSumfile)
	require.NoError(t, err)

	if !strings.Contains(sig, hash) {
		assert.Contains(t, sig, hash)
	}
}

func TestNewFromFiles(t *testing.T) {
	s, err := NewFromFiles(testKeyfile, testPubfile)
	require.NoError(t, err)

	if _, ok := s.Entity.Identities[testKeyName]; !ok {
		assert.NotNil(t, k, "Expected to load a key for user %q", testKeyName)
	}
}

func TestDigestFile(t *testing.T) {
	hash, err := DigestFile(testChartfile)
	require.NoError(t, err)

	sig, err := readSumFile(testSumfile)
	require.NoError(t, err)

	if !strings.Contains(sig, hash) {
		assert.Contains(t, sig, hash)
	}
}

func TestDecryptKey(t *testing.T) {
	k, err := NewFromKeyring(testPasswordKeyfile, testPasswordKeyName)
	require.NoError(t, err)

	if !k.Entity.PrivateKey.Encrypted {
		require.Fail(t, "Key is not encrypted")
	}

	// We give this a simple callback that returns the password.
	if err := k.DecryptKey(func(_ string) ([]byte, error) {
		return []byte("secret"), nil
	}); err != nil {
		require.NoError(t, err)
	}

	// Re-read the key (since we already unlocked it)
	k, err = NewFromKeyring(testPasswordKeyfile, testPasswordKeyName)
	require.NoError(t, err)
	// Now we give it a bogus password.
	if err := k.DecryptKey(func(_ string) ([]byte, error) {
		return []byte("secrets_and_lies"), nil
	}); err == nil {
		require.Fail(t, "Expected an error when giving a bogus passphrase")
	}
}

func TestClearSign(t *testing.T) {
	signer, err := NewFromFiles(testKeyfile, testPubfile)
	require.NoError(t, err)

	metadataBytes := loadChartMetadataForSigning(t, testChartfile)

	// Read the chart file data
	archiveData, err := os.ReadFile(testChartfile)
	require.NoError(t, err)

	sig, err := signer.ClearSign(archiveData, filepath.Base(testChartfile), metadataBytes)
	require.NoError(t, err)
	t.Logf("Sig:\n%s", sig)

	if !strings.Contains(sig, testMessageBlock) {
		assert.Contains(t, sig, testMessageBlock)
	}
}

func TestMixedKeyringRSASigningAndVerification(t *testing.T) {
	signer, err := NewFromFiles(testKeyfile, testMixedKeyring)
	require.NoError(t, err)

	require.NotEmpty(t, signer.KeyRing, "expected signer keyring to be loaded")

	hasEdDSA := false
	for _, entity := range signer.KeyRing {
		if entity.PrimaryKey != nil && entity.PrimaryKey.PubKeyAlgo == packet.PubKeyAlgoEdDSA {
			hasEdDSA = true
			break
		}

		for _, subkey := range entity.Subkeys {
			if subkey.PublicKey != nil && subkey.PublicKey.PubKeyAlgo == packet.PubKeyAlgoEdDSA {
				hasEdDSA = true
				break
			}
		}

		if hasEdDSA {
			break
		}
	}

	assert.True(t, hasEdDSA, "expected %s to include an Ed25519 public key", testMixedKeyring)

	require.NotNil(t, signer.Entity, "expected signer entity to be loaded")
	require.NotNil(t, signer.Entity.PrivateKey, "expected signer private key to be loaded")
	assert.Equal(t, packet.PubKeyAlgoRSA, signer.Entity.PrivateKey.PubKeyAlgo, "expected RSA key")

	metadataBytes := loadChartMetadataForSigning(t, testChartfile)

	archiveData, err := os.ReadFile(testChartfile)
	require.NoError(t, err)

	sig, err := signer.ClearSign(archiveData, filepath.Base(testChartfile), metadataBytes)
	require.NoError(t, err, "failed to sign chart")

	verification, err := signer.Verify(archiveData, []byte(sig), filepath.Base(testChartfile))
	require.NoError(t, err, "failed to verify chart signature")

	require.NotNil(t, verification.SignedBy, "expected verification to include signer")
	require.NotNil(t, verification.SignedBy.PrimaryKey, "expected verification to include signer primary key")
	assert.Equal(t, packet.PubKeyAlgoRSA, verification.SignedBy.PrimaryKey.PubKeyAlgo, "expected verification to report RSA key")

	_, ok := verification.SignedBy.Identities[testKeyName]
	assert.True(t, ok, "expected verification to be signed by %q", testKeyName)
}

// failSigner always fails to sign and returns an error
type failSigner struct{}

func (s failSigner) Public() crypto.PublicKey {
	return nil
}

func (s failSigner) Sign(_ io.Reader, _ []byte, _ crypto.SignerOpts) ([]byte, error) {
	return nil, errors.New("always fails")
}

func TestClearSignError(t *testing.T) {
	signer, err := NewFromFiles(testKeyfile, testPubfile)
	require.NoError(t, err)

	// ensure that signing always fails
	signer.Entity.PrivateKey.PrivateKey = failSigner{}

	metadataBytes := loadChartMetadataForSigning(t, testChartfile)

	// Read the chart file data
	archiveData, err := os.ReadFile(testChartfile)
	require.NoError(t, err)

	sig, err := signer.ClearSign(archiveData, filepath.Base(testChartfile), metadataBytes)
	if err == nil {
		require.Fail(t, "didn't get an error from ClearSign but expected one")
	}

	if sig != "" {
		require.Empty(t, sig, "expected an empty signature after failed ClearSign")
	}
}

func TestVerify(t *testing.T) {
	signer, err := NewFromFiles(testKeyfile, testPubfile)
	require.NoError(t, err)

	// Read the chart file data
	archiveData, err := os.ReadFile(testChartfile)
	require.NoError(t, err)

	// Read the signature file data
	sigData, err := os.ReadFile(testSigBlock)
	require.NoError(t, err)

	if ver, err := signer.Verify(archiveData, sigData, filepath.Base(testChartfile)); err != nil {
		assert.NoError(t, err, "Failed to pass verify")
	} else if len(ver.FileHash) == 0 {
		assert.NotEmpty(t, ver.FileHash, "Verification is missing hash.")
	} else if ver.SignedBy == nil {
		assert.NotEmpty(t, ver.SignedBy, "No SignedBy field")
	} else if ver.FileName != filepath.Base(testChartfile) {
		assert.Equal(t, "hashtest-0.1.0.tgz", ver.FileName)
	}

	// Read the tampered signature file data
	tamperedSigData, err := os.ReadFile(testTamperedSigBlock)
	require.NoError(t, err)

	if _, err = signer.Verify(archiveData, tamperedSigData, filepath.Base(testChartfile)); err == nil {
		assert.Fail(t, "Expected tampered sig block to fail")
	}

	switch err.(type) {
	case pgperrors.SignatureError:
		t.Logf("Tampered sig block error: %s (%T)", err, err)
	default:
		assert.Contains(t, err.Error(), "openpgp")
	}
}

// readSumFile reads a file containing a sum generated by the UNIX shasum tool.
func readSumFile(sumfile string) (string, error) {
	data, err := os.ReadFile(sumfile)
	if err != nil {
		return "", err
	}

	sig := string(data)
	parts := strings.SplitN(sig, " ", 2)
	return parts[0], nil
}
